export const ADD_WAREHOUSE_HISTORY_RECORD =
  'ellegia/Warehouse/ADD_WAREHOUSE_HISTORY_RECORD';
export const ADD_WAREHOUSE_HISTORY_RECORD_SUCCESS =
  'ellegia/Warehouse/ADD_WAREHOUSE_HISTORY_RECORD_SUCCESS';
export const LOAD_WAREHOUSE_HISTORY =
  'ellegia/Warehouse/LOAD_WAREHOUSE_HISTORY';
export const LOAD_WAREHOUSE_HISTORY_SUCCESS =
  'ellegia/Warehouse/LOAD_WAREHOUSE_HISTORY_SUCCESS';
